# config
cover: /img/bg_img.jpg
logo: /img/logo.png
top_saying: 
- title: "Deepen's Blog"
- content: "<br/><br/><br/><br/><br/><br/><br/>A Craving For Cognition <br/> Welcome To Deepen's Blog!"
bottom_saying: "每一个不曾起舞的日子都是对生命的辜负。 —— 尼采《查拉图斯特拉如是说》"
# Content
excerpt_link: "Read More"

rss: /atom.xml

highlightjs: vs

#Works
# works:
# - works_name: AAA
#   works_url: /
# - works_name: BBB
#   works_url: /atom.xml

#duoshuo name duoshuo 是个网页评论的插件
duoshuo:  Deepen

#disqus name  Disqus 是个网页评论的插件
disqus_shortname: Deepen

#fancybox
fancybox: true

# Miscellaneous
github: https://github.com/
twitter: https://twitter.com/
facebook: https://www.facebook.com/
google: https://google.com/
weibo: http://weibo.com/

#about  timeline
timeline:
- num: 1
  word: 2014/06/12-Start
- num: 2
  word: 2014/11/29-XXX
- num: 3
  word: 2015/02/18-DDD
- num: 4
  word: More

#Links
links:
- name: Deepen
  link: http://www.izalco.cn

# Local search
# Dependencies: https://github.com/flashlab/hexo-generator-search
local_search:
  enable: true
  # if auto, trigger search by changing input
  # if manual, trigger search by pressing enter key or search button
  trigger: auto
  # show top n results per article, show all results by setting to -1
  top_n_per_article: 2
